src/init.js

Here is the [issue](https://github.com/Workiva/karma-jspm/issues/30) that describes the problem.

CP-300 Fixed: path separator problem that causing systemjs fail to import source and test files properly on windows.

---

package.json

https://github.com/Workiva/karma-jspm/pull/31
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.1...Release_1.1.2
How To +10/QA
-------------
```bash
git clone git@github.com:Workiva/karma-jspm.git
cd karma-jspm
git fetch && git checkout Release_1.1.2
Run unit tests
```

CP-301 Release karma-jspm 1.1.2

---

package.json

https://github.com/Workiva/karma-jspm/pull/33
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.2...Release_1.1.3
How To +10/QA
-------------
```bash
git clone git@github.com:Workiva/karma-jspm.git
cd karma-jspm
git fetch && git checkout Release_1.1.3
Run unit tests
```

CP-345 Release karma-jspm 1.1.3

---

package.json

https://github.com/Workiva/karma-jspm/pull/35
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.3...Release_1.1.4
How To +10/QA
-------------
```bash
git clone git@github.com:Workiva/karma-jspm.git
cd karma-jspm
git fetch && git checkout Release_1.1.4
Run unit tests
```

CP-381 Release karma-jspm 1.1.4

---

package.json

https://github.com/Workiva/karma-jspm/pull/48
https://github.com/Workiva/karma-jspm/pull/50
https://github.com/Workiva/karma-jspm/pull/47
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.4...Release_1.1.5

CP-544 Release karma-jspm 1.1.5

---

README.md

CP-734 Update README to mention of plugin configuration

---

package.json

https://github.com/Workiva/karma-jspm/pull/61
https://github.com/Workiva/karma-jspm/pull/62
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/1.1.5...Release_2.0.0-beta.1

CP-592 Release karma-jspm 2.0.0-beta.1

---

README.md

CP-762 remove reference to es6-module-loader

---

package.json

https://github.com/Workiva/karma-jspm/pull/53
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.0-beta.1...Release_2.0.1-beta.1

CP-768 Release karma-jspm 2.0.1-beta.1

---

src/adapter.js

This should fix issue #56 where file import errors would not be reported

CP-792 Dont wrap error throwing in a setTimeout, fix #56

---

package.json

https://github.com/Workiva/karma-jspm/pull/76
https://github.com/Workiva/karma-jspm/pull/80
https://github.com/Workiva/karma-jspm/pull/84
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.1-beta.1...Release_2.0.1-beta.2

CP-776 Release karma-jspm 2.0.1-beta.2

---

package.json

https://github.com/Workiva/karma-jspm/pull/81
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.1-beta.2...Release_2.0.1

CP-838 Release karma-jspm 2.0.1

---

package.json

https://github.com/Workiva/karma-jspm/pull/100
https://github.com/Workiva/karma-jspm/pull/105
https://github.com/Workiva/karma-jspm/pull/102
https://github.com/Workiva/karma-jspm/pull/94
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.1-beta.2...Release_2.0.2

CP-840 Release karma-jspm 2.0.2

---

package.json

https://github.com/Workiva/karma-jspm/pull/115
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.2...Release_2.0.3

CP-1076 Release karma-jspm 2.0.3

---

package.json

Update gulp-jasmine dependency

CP-1446 Update gulp-jasmine dependency - fixes #133

---

README.md

Add --save-dev to install instructions

CP-1454 Update README.md, karma-jspm 3.11.2016

---

README.md
src/init.js
test/testInit.spec.js

Added an option to pass a jspm.browser.js file needed for JSPM 0.17 Beta.

CP-1447 Support for JSPM 0.17 Beta

---

src/init.js

CP-1765 Move jspm file pattern to end of served files

---

README.md
src/init.js

I rebased this branch to resolve merge conflicts: https://github.com/sutoiku/karma-jspm/pull/126
@AurelienRibon 
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf @jayudey-wf

CP-1358 [rebase] Add option to not cache jspm_packages

---

package.json

https://github.com/Workiva/karma-jspm/pull/131
https://github.com/Workiva/karma-jspm/pull/149
https://github.com/Workiva/karma-jspm/pull/154
https://github.com/Workiva/karma-jspm/pull/101
https://github.com/Workiva/karma-jspm/pull/167
https://github.com/Workiva/karma-jspm/pull/156
=======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.1.1...Release_2.2.0

CP-1771 Release karma-jspm 2.2.0

---

package.json

Pulls Included in Release:
* [Fix "Error" when using jspm v0.17.0-beta.35](https://github.com/Workiva/karma-jspm/pull/183)
* [CP-2409 Update glob dependency](https://github.com/Workiva/karma-jspm/pull/173)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.2.0...version-bump-karma-jspm-2-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/karma-jspm/compare/2.2.0...2.2.1

CP-2040 Release karma-jspm 2.2.1
