computmaxer/karma-jspm

src/adapter.js

- can't use karma-jspm to test in IE8
- `System['import']` instead of `System.import`
- `['catch']` instead of `.catch`
- unit tests pass
@maxwellpeterson-wf 
@evanweible-wf 
@charliekump-wf 
@jayudey-wf

CP-344 Karma-jspm IE8 fix

---

src/init.js

that's like the first rule of javascript

CP-380 properly declare variables as local, not as globals

---

src/init.js
test/testInit.spec.js

If you would try to run karma from different directory then the one where the karma.conf.js is located then karma-jspm would not resolve file locations correctly. This is due to usage of process.cwd() instead of basePath.
This pull request fixes this issue.

CP-545 Allow karma (with karma-jspm) to be run from different directory then karma.conf.js file's dir

---

README.md
src/adapter.js
src/init.js

if the jspm conf section inside the karma.conf file contains a paths object, this will be used to override path settings. This is helpful if your test environment needs to have different basepaths compared to your production environment.
The Aurelia Team uses karma-jspm as a core workflow tool for unit testing across all repos. This feature would be very important in order to get our test suite working properly.

CP-591 customizable paths

---

src/adapter.js
src/init.js
test/testInit.spec.js

SystemJS 0.17+ requires the baseURL to be configured first and doesn't allow to change it once set. Also, es6-module-loader is not needed anymore. It has been replaced with systemjs-polyfills which are a stripped down version of es6-module-loader.

CP-727 Fix compatibility with SystemJS 0.17+

---

package.json
src/init.js
test/testInit.spec.js

One could also set usePolling to false and pray.

CP-767 Save CPU cycles by not watching jspm_packages directory for changes.

---

.gitignore

Fixes #71. This will prevent the .idea directory from showing up in the npm artifact.
**Source:**
- None.
**Tests:**
- None.
- None.
- CI passes
@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

CP-774 remove .idea folder

---

src/adapter.js

fixes https://github.com/Workiva/karma-jspm/issues/77
Config.js is loaded after the overrides causing 404 errors on all files. When you move the override to after karma has loaded, the overrides work and tests run normally again.

 CP-821 Move overrides to after karma has loaded

---

src/adapter.js

In my karma.conf.js file I was using the jspm { useBundles: false } configuration as shown below.  It wasn't honoring that setting and was trying to load my bundles even if I set it to false.  My change is to move where the exclusion of the SystemJS bundles is performed, and changes how we do it.
In the 0.18.x versions of SystemJS, they only add or update to existing bundle configuration with the System.config method.  See [core.js](https://github.com/systemjs/systemjs/blob/master/lib/core.js).  You can't set it back to an empty map with System.config.
karma-jspm is loading in my "./config.js" file which has bundles defined in it and then it's being configured and can't be removed with the System.config call.  I'm open to alternative implementations, but this one is working for me …

CP-837 Fix to honor the "useBundles" jspm Karma configuration option

---

src/adapter.js

Fixes #93 
**Source:**
- Move null check of System above first usage
- minor style fixes
**Tests:**
- No change
- None
- Ensure karma-jspm still works with another Workiva repository
@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

CP-899 Move System null-check to a useful location

---

README.md
src/adapter.js
src/init.js

Made the module name computation configurable.

CP-1006 Strip extension config

---

src/adapter.js
src/init.js

Fixes #104 
Error: Module interpreted as global module format, but called System register
Solution: Add support to custom meta in karma-jspm config.
Thanks @larrifax for the help.

CP-1068 Fixes #104: Module interpreted as global module format

---

src/adapter.js

We would like to make the order, in which modules are loaded, deterministic. They should be imported in the order specified in `karma.conf.js`. E.g. given this configuration:
jspm: {
serveFiles: ['**/*'],
loadFiles: ['polyfills.js', '**/*.specs.js']
}
The current implementation would attempt to load all modules simultaneously. This can lead to different behavior between test runs, especially in the above case, where the first module adds some global polyfills other modules rely on.
With this changeset, all files specified in the `loadFiles` array will be imported sequentially.
From a perfomance perspective: we could not notice any difference between simultaneous/sequential import, tested in a project with about 400 tests and about 170 modules.

CP-1061 Import modules in the order they were specified in config

---

src/init.js
test/testInit.spec.js

Forces file reread in watch cycle
(required for tests in current edit)
Additionally common problem with testing on windows fixed
Closes #114 #113

CP-1340 feat(config): nocache support for jspm.loadFiles Closes #114  (additionally #113)

---

src/adapter.js

Fixes #128
The issue in #128 was that if the `System.import()` function failed, then all the browsers would disconnect with a "Potentially unhandled rejection". This is mostly annoying for `SyntaxErrors`.
By catching the errors from System.import, and redirecting the message to karma.error(), karma-jspm is improved in the following ways:
- The error is instead printed nicely in the terminal, allowing the user to understand the error.
- The the browsers stay alive, such that the user can simply fix the syntax error and save, triggering a new test run.
- Not having to restart karma every time you make a syntax error.
Before a syntax error would result in the following output:
PhantomJS 2.1.1 (Linux 0.0.0) ERROR: 'Potentially unhandled rejection [3] eval@[native code] …

CP-1392 Redirected errors during System().import to karma().error.

---

package.json

https://github.com/Workiva/karma-jspm/pull/130, Redirected errors during System.import to karma.error.
https://github.com/Workiva/karma-jspm/pull/134, Update gulp-jasmine dependency - fixes #133
https://github.com/Workiva/karma-jspm/pull/137  Update README.md, karma-jspm 
https://github.com/Workiva/karma-jspm/pull/129  Support for JSPM 0.17 Beta
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.0.3...Release_2.1.0

CP-1341 Release karma-jspm 2.1.0

---

package.json

CP-1765  - Move jspm file pattern to end of served files https://github.com/Workiva/karma-jspm/pull/148
CP-1358  - Add option to not cache jspm_packages https://github.com/Workiva/karma-jspm/pull/151
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/karma-jspm/compare/2.1.0...Release_2.1.1

CP-1466 Release karma-jspm 2.1.1

---

index.js
src/init.js
test/testInit.spec.js

Fixes #121
I was quite annoyed that `karma-jspm` didn't load new files when they were added. So I found out that there is a `file_list_modified` event emitted from `karma`, when the file list changes. I simply injected the emitter and wrapped the `expandedFiles` assignment in it.
I have tested the change against one of my own projects, and running karma in watch mode now correctly loads new files when I add them.
Hope you like it ;-)

CP-1770 expandedFiles now update when files are added/removed.

---

src/init.js
test/testInit.spec.js

This change enables the full [file description](http://karma-runner.github.io/0.13/config/files.html) capabilities of karma to the `loadFiles` array instead of only passing through the nocache flag.
For example you can now disable watching for changes on the files you want to load.
I use this feature to only watch bundles for changes, which integrates gracefully with jspm's [development bundling](http://jspm.io/0.17-beta-guide/development-bundling.html) feature (you can reuse your bundle you built for the dev server to execute your tests by providing your spec modules within the bundle).

CP-1789 Enable karma file descriptions for loadFiles array

---

gulpfile.js
package.json
test/jasmine.json

The problem with the gulp-jasmine plugin was that failing tests
do not make the travis build fail.
By using plain jasmine we achieve this failing of the tests.
As a nice side effect our dependencies are much more light-weight
and the tests are executed faster.
Resolves #153
Note: At the moment this test fails, since the tests are failing in the master branch.

CP-1790 Replace gulp-jasmine by plain jasmine

---

.eslintrc
package.json
src/adapter.js
src/init.js
test/testInit.spec.js

Make use of basic [eslint](http://eslint.org/) rules and fixed warnings

CP-1062 eslint, karma-jspm

---

src/init.js
test/testInit.spec.js

we have a slightly big project that involves several connected projects. We often load more then one files that contains systemjs configuration.
(using `jspm.browser.js` can be considered a specialized use case, and the current jspm.browser should be deprecated IMO)

CP-1962 support jspm.config as array

---

src/init.js
test/testInit.spec.js

CP-2039 fix(init): issue #162

---

package.json

Currently installing `karma-jspm` gives a warning:
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
This PR updates the `glob` dependency to the most recent version which uses an updated `minimatch` version as well.
I ran the tests after the change and they all still pass.
This PR should also fix #166.

CP-2409 Update glob dependency

---

src/adapter.js

jspm v0.17.0-beta.35 throw an error when it used with karma-jspm v2.2.0: 
```bash
Uncaught Error: Setting `SystemJS.bundles` directly is no longer supported. Use `SystemJS.config({ bundles: ... })`.
```
This commit will solve this issue. Instead of `System.bundles = [];`, `System.config({ bundles: [] });` should be used.

Fix "Error" when using jspm v0.17.0-beta.35

---

README.md
src/init.js
test/testInit.spec.js

This is the case in jspm 0.17 beta >33 because systemjs no longer includes system-polyfills.

Add es6-promise polyfill if system-polyfills doesn't exist.
